//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerSaleHistory
    {
        public int id { get; set; }
        public int productId { get; set; }
        public int partnerId { get; set; }
        public int quantity { get; set; }
        public System.DateTime saleDate { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual Product Product { get; set; }
    }
}
